name: Deploy to Google Cloud

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Sync static files to the Cloud Storage bucket
      - name: Sync static files to Cloud Storage
        run: |
          echo "${{ secrets.GCLOUD_AUTH }}" > $HOME/gcloud.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud.json
          gcloud config set project hci-iteration2
          gsutil -m rsync -r . gs://hci-iteration2/public

      # Step 2: Install dependencies for the Node.js server
      - name: Install dependencies
        run: npm install

      # Step 3: Build the Docker image for the Node.js server
      - name: Build Docker image
        run: docker build -t gcr.io/hci-iteration2/hci .

      # Step 4: Push the Docker image to Google Container Registry
      - name: Push Docker image to GCR
        run: docker push gcr.io/hci-iteration2/hci

      # Step 5: Deploy the Node.js server to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud auth configure-docker
          gcloud run deploy hci-00001-jvm \
            --image gcr.io/hci-iteration2/hci \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      # Step 6: Set OpenAI API Key
      - name: Set OpenAI API Key
        run: echo "::set-env name=OPENAI_API_KEY::${{ secrets.OPENAI }}"

    options:
      logging: CLOUD_LOGGING_ONLY
