steps:
# Step 1: Sync static files to the Cloud Storage bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', '.', 'gs://hci-iteration2/public']

# Step 2: Install dependencies for the Node.js server
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Step 3: Build the Docker image for the Node.js server
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t', 'gcr.io/hci-iteration2/hci-00001-jvm', '.'
  ]

# Step 4: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 'gcr.io/hci-iteration2/hci-00001-jvm'
  ]

# Step 5: Deploy the Node.js server to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'hci-00001-jvm',
    '--image', 'gcr.io/hci-iteration2/hci-00001-jvm',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
